### ISSUE TITLE
TLS error

### ISSUE THREAD

**Issue by jmangan68** [tomlarse/Install-Git#2]
When running the script, I get the following error: Invoke-RestMethod : The request was aborted: Could not create SSL/TLS secure channel. I added the following to your script and was able to get around the error: [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12;

**Comment by tomlarse** [comment]
Thanks! 

Seen quite a lot of these popping up lately. Do you want to submit a pull request or should I just add it myself? :)

**Comment by jmangan68** [comment]
I will try and get a pull request in later today

**Comment by tomlarse** [comment]
Sorry, completely forgot about this! Thanks a lot for the contribution. The change is live on PSGallery now.
